# Generated by Django 5.2.1 on 2025-06-16 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='author',
            field=models.ManyToManyField(related_name='books', to='user.author'),
        ),
        migrations.AlterField(
            model_name='genre',
            name='name',
            field=models.CharField(choices=[('R', 'ROMANCE'), ('D', 'COMEDY'), ('P', 'POLITICS'), ('F', 'FINANCE')], default='F', max_length=1, unique=True),
        ),
    ]
